In [68]:
%load_ext autoreload
%autoreload 2
from recommend import load_model, recommend
import warnings
warnings.filterwarnings('ignore')
from collections import defaultdict
import pandas as pd
import numpy as np

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [119]:
try:
    model = load_model()
except ValueError:
    pass

In [ ]:
nolikes = defaultdict(lambda: {'random': 0, 'interested_only': 0, 'topic': 0})
scores = defaultdict(lambda: {'random': 0, 'interested_only': 0, 'topic': 0})
interested = defaultdict(lambda: {'random': 0, 'interested_only': 0, 'topic': 0})
relevances = defaultdict(lambda: {'random': 0, 'interested_only': 0, 'topic': 0})

np.random.seed(333)
user_ids = np.random.choice(range(45963), 2000, replace=False)
for i, user_id in enumerate(user_ids):
    if i % 100 == 0:
        print(i, user_id)
#     for method in ['low_tolerance', 'high_tolerance', 'topic']:
    for method in ['random', 'interested_only', 'topic']:
        liked, notliked, i, score, relevance = recommend(model, user_id, k=10, mode=method, display=False)
        nolikes[user_id][method] = len(notliked)
        scores[user_id][method] = score
        interested[user_id][method] = i
        relevances[user_id][method] = relevance

0 38941
100 39526
200 37612
300 13684
400 26237

In [255]:
df = pd.DataFrame.from_dict(nolikes, 'index')
df.to_csv('results/ranking_nolikes.csv')
df.describe()

           random         top       topic
count  920.000000  920.000000  920.000000
mean     4.138043    3.600000    3.625000
std      0.618423    0.846679    0.887358
min      3.000000    2.000000    1.000000
25%      4.000000    3.000000    3.000000
50%      4.000000    4.000000    4.000000
75%      5.000000    4.000000    4.000000
max      6.000000    6.000000    6.000000

In [256]:
df = pd.DataFrame.from_dict(scores, 'index')
df.to_csv('results/ranking_scores.csv')
df.describe()

           random         top       topic
count  920.000000  920.000000  920.000000
mean     0.682512    0.749748    0.749862
std      0.029317    0.046151    0.046705
min      0.571979    0.578626    0.526270
25%      0.661980    0.726276    0.727293
50%      0.681368    0.762578    0.763548
75%      0.699823    0.783758    0.783081
max      0.787382    0.830649    0.831310

In [257]:
df = pd.DataFrame.from_dict(relevances, 'index')
df.to_csv('results/ranking_relevances.csv')
df.describe()

           random         top       topic
count  920.000000  920.000000  920.000000
mean     0.404288    0.592815    0.594289
std      0.067322    0.027855    0.030742
min      0.187581    0.528008    0.524466
25%      0.356970    0.572266    0.571497
50%      0.402057    0.591037    0.593101
75%      0.444583    0.611456    0.613012
max      0.636633    0.685688    0.697689

In [258]:
df = pd.DataFrame.from_dict(interested, 'index')
df.to_csv('results/ranking_vs.csv')
df.describe()

           random    top  topic
count  920.000000  920.0  920.0
mean     7.569565   10.0   10.0
std      0.853558    0.0    0.0
min      5.000000   10.0   10.0
25%      7.000000   10.0   10.0
50%      8.000000   10.0   10.0
75%      8.000000   10.0   10.0
max     10.000000   10.0   10.0